config/routes.rb
Rails.application.routes.draw do
  resources :teams
  devise_for :users, controllers: {:registrations => "registrations"}

  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'

  resources :teams, shallow: true do
    resources :users
  end
  resources :users, shallow: true do
    resources :comments
    resources :tasks
  end

  resources :projects, shallow: true do
    resources :tasks
  end
  resources :tasks, shallow: true do
    resources :posts
  end

  resources :posts, shallow: true do
    resources :comments
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  def about
  end
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>

<h1>About Us</h1>
<p>
<h3>
 Tumilovich Denis ;)
</h3>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Email: tumilovi4@gmail.com</p>
<p>
  <a href="https://www.linkedin.com/in/freerain">My LinkedIn page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>Help!!!!</h1>

app/views/static_pages/home.html.erb
<div class="center hero-unit">

  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the sample application.
  </h2>
</div>

<ul class="nav nav-justified" type="">
  <% if can? :index, Project %>
      <li><%= link_to "Project", projects_path %></li>
  <% end %>
  <% if can? :index, Team %>
      <li><%= link_to "Teams", teams_path %></li>
  <% end %>
  <% if can? :index, Task %>
      <li><%= link_to "Tasks", tasks_path %></li>
  <% end %>
  <% if can? :index, Post %>
      <li><%= link_to "Posts", posts_path %></li>
  <% end %>
  <% if can? :index, User %>
      <li><%= link_to "Users", users_path %></li>
  <% end %>
</ul>