config/routes.rb
Rails.application.routes.draw do
  resources :teams
  devise_for :users, controllers: {:registrations => "registrations"}

  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'

  resources :teams, shallow: true do
    resources :users
  end
  resources :users, shallow: true do
    resources :comments
    resources :tasks
  end

  resources :projects, shallow: true do
    resources :tasks
  end
  resources :tasks, shallow: true do
    resources :posts
  end

  resources :posts, shallow: true do
    resources :comments
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :posts, :dependent => :destroy
  belongs_to :user
  belongs_to :project
  validates :title, presence: true, length: {maximum: 80}, uniqueness: {case_sensitive: false}
  validates :status, length: {maximum: 15}
  validates :start_date, date: {after: Proc.new { Date.today -1 }, message: 'Must be after yesterday'},
            on: :create
  validates :due_date, date: {after: Proc.new { :start_date }, message: 'Must be after Start day'},
            on: :create


  def self.get_complete(commit, tasks)
    if commit
      tasks.reject { |task| task.status!='complete' }
    else
      tasks
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  #before_action :set_project, only: [:new, :create]
  load_and_authorize_resource
  # GET /tasks
  # GET /tasks.json
  def index

    if params[:user_id].present?
      @user=User.find_by_id(params[:user_id])
      @tasks=@user.tasks
      @tasks=Task.get_complete(params[:commit], @tasks)
      render
    end
    if params[:project_id].present?
      @project = Project.find(params[:project_id])
      @tasks=@project.tasks
      @tasks=Task.get_complete(params[:commit], @tasks)
    else
      @tasks=Task.all
      @tasks=Task.get_complete(params[:commit], @tasks)
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end


  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.project_id=@project.id
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_url(@task.project_id), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_url(@task.project_id), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_url(@task.project_id), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:title, :status, :start_date, :due_date, :estimation, :project_id, :user_id)
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
    <% if @task.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
            <% @task.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :status %><br>
      <%= f.text_field :status %>
    </div>
    <!--
    <div class="field">
      <%#= f.label :user %><br>
      <%#= f.select :user, @users.%>
    </div>
    -->
    <div class="field">
      <%= f.label :start_date %><br>
      <%= f.date_select :start_date %>
    </div>
    <div class="field">
      <%= f.label :due_date %><br>
      <%= f.date_select :due_date %>
    </div>
    <div class="field">
      <%= f.label :estimation %><br>
      <%= f.text_field :estimation %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', @task %>

app/views/tasks/index.html.erb
<% if @project==nil&&@user==nil %>
    <%= form_tag tasks_path, :method => 'get' do %>
        <p>
          <%= submit_tag "Get completed Tasks for all" %>
        </p>
    <% end %>
<% end %>
<% if @project!=nil %>
    <%= form_tag project_tasks_path(:project_id => @project), :method => 'get' do %>
        <p>
          <%= submit_tag "Get completed Tasks for project" %>
        </p>
    <% end %>
<% end %>
<% if @user!=nil %>
    <%= form_tag user_tasks_path(:user_id => @user), :method => 'get' do %>
        <p>
          <%= submit_tag "Get completed Tasks for user" %>
        </p>
    <% end %>
<% end %>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Title</th>
    <th>Status</th>
    <th>Start date</th>
    <th>Due date</th>
    <th>Estimation</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.title, task %></td>
        <td><%= task.status %></td>
        <td><%= task.start_date %></td>
        <td><%= task.due_date %></td>
        <td><%= task.estimation %></td>
        <% if can? :update, Task %>
            <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <% end %>
        <% if can? :destroy, Task %>
            <td><%= link_to 'Destroy', task, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>


<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/tasks/show.html.erb
<h5>
  <strong>Title:</strong>
  <%= @task.title %>
</h5>

<h5>
  <strong>Status:</strong>
  <%= @task.status %>
</h5>
<h5>
  <strong>User:</strong>
  <%= @task.user.email %>
</h5>
<h5>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</h5>

<h5>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</h5>

<h5>
  <strong>Estimation:</strong>
  <%= @task.estimation %>
</h5>
<h5>
  <strong>Tasks posts</strong>
  <%= link_to pluralize(@task.posts.size, 'post'), task_posts_path(:task_id => @task) %>
</h5>
<% if can? :create, Post %>
    <%= link_to 'Add New Post', new_task_post_path(:task_id => @task) %>
<% end %>
<% if can? :update, Task %>
    <%= link_to 'Edit', edit_task_path(@task) %> |
<% end %>