config/routes.rb
Rails.application.routes.draw do
  resources :teams
  devise_for :users, controllers: {:registrations => "registrations"}

  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'

  resources :teams, shallow: true do
    resources :users
  end
  resources :users, shallow: true do
    resources :comments
    resources :tasks
  end

  resources :projects, shallow: true do
    resources :tasks
  end
  resources :tasks, shallow: true do
    resources :posts
  end

  resources :posts, shallow: true do
    resources :comments
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  has_and_belongs_to_many :teams
  validates :name, length: {maximum: 130},presence: true,uniqueness: {case_sensitive: false}
  validates :summary,length: {maximum: 50}, presence: true
  validates :start_date, date: {after: Proc.new { Date.today -1}, message: 'Must be after yesterday'},
            on: :create
  validates :end_date, date: {after: Proc.new {:start_date}, message: 'Must be after Start day'},
            on: :create

  private
  def self.search_by_name(search_name)
    projects=Project.where('name like ?', "%#{search_name}%")
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #before_action :set_project, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /projects
  # GET /projects.json
  def index
    if params[:search_name]
      @projects=Project.search_by_name(params[:search_name])
    else
      @projects = Project.all
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    # authorize! :create, @project
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :summary, :start_date, :end_date)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= form_tag projects_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search_name %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>
<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Summary</th>
    <th>Start date</th>
    <th>End date</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= project.summary %></td>
        <td><%= project.start_date %></td>
        <td><%= project.end_date %></td>
        <% if can? :update, Project %>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <% end %>
        <% if can? :destroy, Project %>
            <td><%= link_to 'Destroy', project, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Project %>
    <%= link_to 'New Project', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h5>
  <strong>Name:</strong>
  <%= @project.name %>
</h5>

<h5>
  <strong>Summary:</strong>
  <%= @project.summary %>
</h5>

<h5>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</h5>

<h5>
  <strong>End date:</strong>
  <%= @project.end_date %>
</h5>
<h5>
  <strong>Tasks</strong>
  <%= link_to pluralize(@project.tasks.size, 'task'), project_tasks_path(:project_id => @project) %>
</h5>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%=link_to 'New Task', new_project_task_path(:project_id => @project) %>