config/routes.rb
Rails.application.routes.draw do
  resources :teams
  devise_for :users, controllers: {:registrations => "registrations"}

  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'

  resources :teams, shallow: true do
    resources :users
  end
  resources :users, shallow: true do
    resources :comments
    resources :tasks
  end

  resources :projects, shallow: true do
    resources :tasks
  end
  resources :tasks, shallow: true do
    resources :posts
  end

  resources :posts, shallow: true do
    resources :comments
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, :dependent => :delete_all
  belongs_to :task
  validates :content, length: {maximum: 50}, presence: true
  validates :task , presence: true, inclusion: {in: Task.all}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :set_task, only: [:new, :create]
  load_and_authorize_resource
  # GET /posts
  # GET /posts.json
  def index
    if params[:task_id].present?
      @task = Task.find(params[:task_id])
      @posts=@task.posts
    else
      @posts = Post.all
    end

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post=Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    unless @post.task_id
      @post.task_id=@task.id
    end
    respond_to do |format|
      if @post.save
        format.html { redirect_to task_url(@post.task_id), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to task_url(@post.task_id), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to task_url(@post.task_id), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def set_task
    @task = Task.find(params[:task_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@task, @post] do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
      <tr>
        <td><%=link_to post.content, post %></td>
        <% if can? :update, Post %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <% end %>
        <% if can? :destroy, Post %>
            <td><%= link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/posts/show.html.erb
<h5>
  <strong>Content:</strong>
  <%= @post.content %>
</h5>


<h2>Posts comments</h2>
<table class ="table">
  <% @post.comments.each do |comment| %>
      <tr >
        <td>
          <%= comment.message %>
        </td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>
</p>
<%= link_to 'New Comment', new_post_comment_path(:post_id=>@post.id) %>
<%= link_to 'Edit', edit_post_path(@post) %> |